name: CI/CD for YOLO SQS Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to copy the requirements.txt to the server
      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -r . $USER@$HOST:/home/$USER/yolo_api

          ssh -i ssh_key $USER@$HOST << EOF
            cd /home/$USER/yolo_api
            
            if ! cmp -s requirements.txt requirements.txt.bak; then
              echo "requirements.txt has changed, installing dependencies..."
              python -m venv venv || true
              source venv/bin/activate
              pip install -r requirements.txt
              cp requirements.txt requirements.txt.bak
            else
              echo "No changes in requirements.txt"
            fi
            
            sudo systemctl restart yolo_api.service
          EOF
