name: CI/CD for YOLO SQS Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check for changes in requirements.txt
        id: check-requirements
        run: |
          if [ -f /tmp/requirements_hash ]; then
            old_hash=$(cat /tmp/requirements_hash)
          else
            old_hash=""
          fi
          new_hash=$(sha256sum requirements.txt | cut -d ' ' -f 1)
          echo "old=$old_hash" >> $GITHUB_ENV
          echo "new=$new_hash" >> $GITHUB_ENV

      - name: Install dependencies if requirements.txt changed
        if: ${{ env.old != env.new }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sha256sum requirements.txt | cut -d ' ' -f 1 > /tmp/requirements_hash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          scp -i ssh_key -r . $USER@$HOST:/home/$USER/yolo_api
          ssh -i ssh_key $USER@$HOST << EOF
            cd /home/$USER/yolo_api
            python -m venv venv || true
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart yolo_api.service
          EOF
